
insert into T_MENU (DAY, BRK_FST, LUNCH, DINNER) values ('MON', 'IDLY,SAMBAR,VADA', 'SAMBAR,RASAM,CURD,PORIYAL', 'CHAPPATHI,KURUMA');
insert into T_MENU (DAY, BRK_FST, LUNCH, DINNER) values ('TUE', 'PONGAL,SAMBAR,VADA', 'VEG BRIYANI', 'CHAPPATHI,KURUMA');
insert into T_MENU (DAY, BRK_FST, LUNCH, DINNER) values ('WED', 'UPMA,CHUTNEY', 'CHICKEN BRIYANI', 'CHAPPATHI,KURUMA');
insert into T_MENU (DAY, BRK_FST, LUNCH, DINNER) values ('THU', 'POORI MASALA', 'MUTTON BRIYANI', 'CHAPPATHI,KURUMA');
insert into T_MENU (DAY, BRK_FST, LUNCH, DINNER) values ('FRI', 'DOSA,CHUTNEY', 'EGG BRIYANI', 'CHAPPATHI,KURUMA');

